"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";

type Recipe = {
  id: string; title: string; subtitle: string; swedishTitle: string; description: string;
  protein: string; carb: string; category: string; image?: string;
  prep: number; active: number; total: string; servings: number; occasion: string;
  macros: { kcal: number; protein: number; carbs: number; fat: number; fiber: number };
  ingredients: { heading: string; items: string[] }[];
  steps: { title: string; items: string[] }[];
  tips: string[]; why: string[];
};

const seedRecipes: Recipe[] = [
  { id:"gyros-i-pita", title:"GYROS I PITA", subtitle:"MED FETA & VITLÖKSSÅS", swedishTitle:"Gyros i pita med feta och vitlökssås", description:"Varm pita fylld med kryddig gyros, krispiga grönsaker, snabbpicklad rödlök, fetaost och krämig vitlökssås.", protein:"Gyros", carb:"Pitabröd", category:"Snabb middag", prep:15, active:15, total:"30 min", servings:2, occasion:"Vardag",
    macros:{kcal:540,protein:38,carbs:42,fat:28,fiber:6}, ingredients:[{heading:"Gyros",items:["250–300 g gyroskebab","2 pitabröd","Några droppar citron"]},{heading:"Grönsaker & tillbehör",items:["2 nävar sallad","1 tomat","10 cm gurka","½ rödlök","40–50 g fetaost"]},{heading:"Vitlökssås",items:["150 g grekisk yoghurt","1 vitlöksklyfta","1 tsk olivolja","½ tsk citronjuice"]}], steps:[{title:"Snabbpickla rödlöken",items:["Blanda vinäger, vatten, socker och salt.","Vänd ner rödlöken och låt stå."]},{title:"Gör vitlökssåsen",items:["Blanda yoghurt, vitlök, olja och citron.","Smaka av med salt och peppar."]},{title:"Stek och bygg",items:["Stek gyrosen med krispiga kanter.","Värm bröden och fyll med alla tillbehör."]}], tips:["Servera extra sås vid bordet.","Citron och kallt mineralvatten passar fint."], why:["Picklad lök balanserar fettet.","Fetaost ger sälta och frisk syra."] },
  { id:"le-filet-de-renne", title:"LE FILET DE RENNE", subtitle:"DU NORD", swedishTitle:"Renytterfilé med rödvinssås", description:"En hyllning till nordiska skogar och franska smaker – mör renytterfilé, silkeslen rödvinssås och rostade grönsaker.", protein:"Ren", carb:"Potatis", category:"Helgmiddag", prep:15, active:45, total:"60 min", servings:2, occasion:"Helg",
    macros:{kcal:550,protein:43,carbs:37,fat:20,fiber:6}, ingredients:[{heading:"Renytterfilé",items:["300–400 g renytterfilé","1 msk neutral olja","1 msk smör","Vitlök och färsk timjan"]},{heading:"Rödvinssås",items:["1 schalottenlök","2 dl rödvin","1 dl kalvfond","1 tsk tomatpuré"]},{heading:"Rostade grönsaker",items:["400 g nypotatis","3–4 morötter","200 g brysselkål","Olivolja och timjan"]}], steps:[{title:"Stek renytterfilén",items:["Bryn köttet runt om och ös med smör.","Låt vila till 52–54°C kärntemperatur."]},{title:"Koka rödvinssåsen",items:["Reducera vin och lök till hälften.","Tillsätt fond och montera med smör."]},{title:"Rosta och servera",items:["Rosta grönsakerna gyllene i 225°C.","Skiva köttet och servera med såsen."]}], tips:["Häll lite extra sås över köttet.","Servera gärna med Syrah eller Rioja."], why:["Ren är mört och viltsmakande.","Rödvinssåsen ger djup och syra."] },
  { id:"civet-delan", title:"CIVET D’ÉLAN", subtitle:"DES FORÊTS DU NORD", swedishTitle:"Älggryta med enbär och rönnbärsgelé", description:"En mustig vilträtt där mört älgkött får koka länge i rödvin med enbär, timjan, rotfrukter och äpple.", protein:"Älg", carb:"Potatis", category:"Långkok", prep:25, active:25, total:"3–4 tim", servings:6, occasion:"Middagsrätt",
    macros:{kcal:580,protein:46,carbs:40,fat:22,fiber:6}, ingredients:[{heading:"Älggryta",items:["800 g älggrytbitar","2 gula lökar","3 morötter","2 palsternackor","1 liten rotselleri"]},{heading:"Kryddor & vätska",items:["6–8 enbär","3 lagerblad","3 kvistar timjan","2 dl rödvin","5 dl kalvfond"]},{heading:"Syra & sötma",items:["1 syrligt äpple","1 msk rönnbärsgelé"]}], steps:[{title:"Bryn köttet",items:["Torka köttet och bryn i omgångar.","Ta upp köttet och lägg åt sidan."]},{title:"Bygg grytan",items:["Fräs grönsaker och kryddor.","Tillsätt vin, fond och kött."]},{title:"Koka långsamt",items:["Sjud under lock i 3–4 timmar.","Avsluta med äpple och rönnbärsgelé."]}], tips:["Grytan blir ännu godare dagen efter.","Servera med rustikt potatismos."], why:["Lång koktid gör älgköttet mört.","Enbär och timjan ger viltkaraktär."] },
  { id:"poulet-au-citron", title:"POULET AU CITRON", subtitle:"ET À L’ESTRAGON", swedishTitle:"Citronkyckling med dragon", description:"Gyllene kyckling i en ljus, örtig citronsås med smör och dragon.", protein:"Kyckling", carb:"Pasta", category:"Vardag", prep:10, active:25, total:"35 min", servings:4, occasion:"Vardag", macros:{kcal:610,protein:44,carbs:58,fat:22,fiber:4}, ingredients:[{heading:"Kyckling",items:["600 g kycklinglårfilé","1 citron","2 dl matlagningsgrädde","Färsk dragon"]},{heading:"Tillbehör",items:["320 g tagliatelle","Sallad efter säsong"]}], steps:[{title:"Bryn",items:["Bryn kycklingen gyllene."]},{title:"Koka såsen",items:["Tillsätt citron, grädde och dragon."]},{title:"Servera",items:["Vänd ihop med nykokt pasta."]}], tips:["Spara lite pastavatten till såsen."],why:["Citronen bryter gräddens fyllighet."] },
  { id:"saumon-roti", title:"SAUMON RÔTI", subtitle:"À L’ANETH", swedishTitle:"Ugnslax med dill och potatis", description:"Saftig lax, brynt smör, dill och rostad småpotatis i enkel nordisk kostym.", protein:"Lax", carb:"Potatis", category:"Snabb middag", prep:10, active:20, total:"30 min", servings:4, occasion:"Vardag", macros:{kcal:570,protein:39,carbs:45,fat:26,fiber:5}, ingredients:[{heading:"Lax",items:["600 g laxfilé","1 citron","1 knippe dill"]},{heading:"Potatis",items:["800 g småpotatis","1 msk olivolja"]}], steps:[{title:"Rosta",items:["Rosta potatisen i 225°C."]},{title:"Baka laxen",items:["Baka laxen till 48–50°C."]},{title:"Servera",items:["Toppa med dill och citron."]}],tips:["En kall yoghurtsås passar bra."],why:["Brynt smör och dill är klassiskt till lax."] },
  { id:"crepes-aux-myrtilles", title:"CRÊPES AUX MYRTILLES", subtitle:"DU MATIN", swedishTitle:"Blåbärspannkakor", description:"Fluffiga små pannkakor med blåbär, lättvispad crème fraîche och lönnsirap.", protein:"Ägg", carb:"Bröd", category:"Frukost", prep:10, active:15, total:"25 min", servings:3, occasion:"Frukost", macros:{kcal:430,protein:13,carbs:61,fat:15,fiber:5}, ingredients:[{heading:"Smet",items:["2,5 dl vetemjöl","2,5 dl mjölk","1 ägg","2 tsk bakpulver"]},{heading:"Servering",items:["2 dl blåbär","Crème fraîche","Lönnsirap"]}],steps:[{title:"Blanda",items:["Vispa ihop en slät smet."]},{title:"Stek",items:["Stek små pannkakor i smör."]},{title:"Servera",items:["Toppa med blåbär."]}],tips:["Vänd pannkakan när bubblor syns."],why:["Bakpulvret gör dem höga och mjuka."] }
];

type Note = { text:string; date:string };
type SyncStatus = { state:string; message:string; last_sync?:string|null; revision?:string|null };

export default function Home() {
  const [recipes,setRecipes]=useState<Recipe[]>(seedRecipes);
  const [query,setQuery]=useState(""); const [protein,setProtein]=useState("Alla"); const [carb,setCarb]=useState("Alla"); const [selected,setSelected]=useState<Recipe|null>(null); const [showAll,setShowAll]=useState(false); const [sortBy,setSortBy]=useState<"name"|"protein"|"carb">("name"); const [archiveName,setArchiveName]=useState(""); const [archiveProtein,setArchiveProtein]=useState("Alla"); const [archiveCarb,setArchiveCarb]=useState("Alla");
  const [ratings,setRatings]=useState<Record<string,number>>(()=>{if(typeof window==="undefined")return {};try{return JSON.parse(localStorage.getItem("carnet-ratings")||"{}");}catch{return {};}}); const [notes,setNotes]=useState<Record<string,Note[]>>(()=>{if(typeof window==="undefined")return {};try{return JSON.parse(localStorage.getItem("carnet-notes")||"{}");}catch{return {};}}); const [panel,setPanel]=useState<"comment"|"change"|null>(null); const [draft,setDraft]=useState("");
  const [sync,setSync]=useState<SyncStatus>({state:"idle",message:"Kontrollerar receptarkivet…"}); const [syncing,setSyncing]=useState(false);
  useEffect(()=>{ fetch("api/recipes").then(r=>r.ok?r.json():Promise.reject()).then(data=>{if(Array.isArray(data)&&data.length)setRecipes(data);}).catch(()=>{}); },[]);
  useEffect(()=>{ fetch("api/sync").then(r=>r.ok?r.json():Promise.reject()).then(setSync).catch(()=>setSync({state:"local",message:"Lokal förhandsvisning"})); },[]);
  useEffect(()=>{ if(!selected)return; fetch(`api/state/${selected.id}`).then(r=>r.ok?r.json():Promise.reject()).then(data=>{setRatings(current=>({...current,[selected.id]:data.rating||0}));setNotes(current=>({...current,[selected.id]:data.notes||[]}));}).catch(()=>{}); },[selected]);
  const proteins=["Alla",...new Set(recipes.map(r=>r.protein))], carbs=["Alla",...new Set(recipes.map(r=>r.carb))];
  const filtered=useMemo(()=>recipes.filter(r=>{const q=query.toLowerCase().trim(); return (protein==="Alla"||r.protein===protein)&&(carb==="Alla"||r.carb===carb)&&(!q||`${r.title} ${r.swedishTitle} ${r.protein} ${r.carb}`.toLowerCase().includes(q));}),[query,protein,carb,recipes]);
  const archive=useMemo(()=>recipes.filter(recipe=>{const name=archiveName.toLocaleLowerCase("sv").trim();return (!name||`${recipe.swedishTitle} ${recipe.title}`.toLocaleLowerCase("sv").includes(name))&&(archiveProtein==="Alla"||recipe.protein===archiveProtein)&&(archiveCarb==="Alla"||recipe.carb===archiveCarb);}).sort((a,b)=>{const av=sortBy==="protein"?a.protein:sortBy==="carb"?a.carb:a.swedishTitle;const bv=sortBy==="protein"?b.protein:sortBy==="carb"?b.carb:b.swedishTitle;return av.localeCompare(bv,"sv",{sensitivity:"base"})||a.swedishTitle.localeCompare(b.swedishTitle,"sv");}),[recipes,archiveName,archiveProtein,archiveCarb,sortBy]);
  const importantIngredients=(recipe:Recipe)=>recipe.ingredients.flatMap(group=>group.items).slice(0,3).join(" · ");
  function rate(id:string,value:number){const next={...ratings,[id]:value};setRatings(next);localStorage.setItem("carnet-ratings",JSON.stringify(next));fetch("api/ratings",{method:"POST",headers:{"Content-Type":"application/json","X-Carnet-Request":"1"},body:JSON.stringify({recipe_id:id,rating:value})}).catch(()=>{});}
  function submitNote(event:FormEvent){event.preventDefault();if(!selected||!draft.trim())return;const kind=panel==="change"?"change":"comment";const prefix=kind==="change"?"Ändringsförslag: ":"";const note={text:prefix+draft.trim(),date:new Date().toLocaleDateString("sv-SE")};const next={...notes,[selected.id]:[...(notes[selected.id]||[]),note]};setNotes(next);localStorage.setItem("carnet-notes",JSON.stringify(next));fetch("api/notes",{method:"POST",headers:{"Content-Type":"application/json","X-Carnet-Request":"1"},body:JSON.stringify({recipe_id:selected.id,kind,text:draft.trim()})}).catch(()=>{});setDraft("");setPanel(null);}
  function syncNow(){setSyncing(true);fetch("api/sync",{method:"POST",headers:{"Content-Type":"application/json","X-Carnet-Request":"1"},body:"{}"}).then(async response=>{const status=await response.json();setSync(status);if(response.ok)return fetch("api/recipes");throw new Error(status.message);}).then(response=>response.json()).then(data=>{if(Array.isArray(data)&&data.length)setRecipes(data);}).catch(error=>setSync({state:"error",message:error instanceof Error?error.message:"Synkroniseringen misslyckades"})).finally(()=>setSyncing(false));}
  return <main>
    <header className="masthead"><button className="wordmark" onClick={()=>setSelected(null)}><span className="crown">♛</span><b>LE CARNET DU NORD</b><small>RECETTES DE LA MAISON</small></button><div className="syncArea"><span className={`syncState ${sync.state}`} title={sync.message}>● {sync.state==="current"?"RECEPTEN ÄR AKTUELLA":sync.state==="error"?"SYNKFEL":"PRIVAT ARKIV"}</span><button onClick={syncNow} disabled={syncing} aria-label="Hämta nya recept från GitHub">{syncing?"Hämtar…":"Uppdatera recept"}</button></div></header>
    {!selected ? <>
      <section className="homeHero"><div><p className="kicker">NORDISKA RÅVAROR · FRANSK SJÄL</p><h1>Vad vill du<br/><i>laga idag?</i></h1></div><div className="searchPanel"><label><span>SÖK I REPERTOAREN</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Namn, protein eller kolhydrat"/></label><div className="selects"><label>PROTEIN<select value={protein} onChange={e=>setProtein(e.target.value)}>{proteins.map(x=><option key={x}>{x}</option>)}</select></label><span>+</span><label>KOLHYDRAT<select value={carb} onChange={e=>setCarb(e.target.value)}>{carbs.map(x=><option key={x}>{x}</option>)}</select></label></div></div></section>
      <section className={`latest ${showAll?"archiveMode":""}`}>
        <div className="latestHead">
          <div><p className="kicker">{showAll?"HELA REPERTOAREN":"SENAST UR KÖKET"}</p><h2>{showAll?"Toutes les recettes":"Les dernières recettes"}</h2></div>
          <div className="archiveToggle"><span>{showAll?archive.length:filtered.length} recept</span><button onClick={()=>{if(!showAll){setArchiveName(query);setArchiveProtein(protein);setArchiveCarb(carb)}setShowAll(value=>!value);requestAnimationFrame(()=>document.querySelector(".latest")?.scrollIntoView({behavior:"smooth"}))}}>{showAll?"Visa de senaste":"Visa alla recept"}</button></div>
        </div>
        {!showAll?<div className="recipeGrid">{filtered.slice(0,6).map((r,i)=><button className={`recipeTile tile${i+1}`} key={r.id} onClick={()=>{setSelected(r);scrollTo(0,0)}}><div className="tileImage">{r.image?<img src={r.image} alt=""/>:<span>{r.protein.slice(0,1)}</span>}<em>{ratings[r.id]?`${ratings[r.id]} ★`:"NYTT"}</em></div><div className="tileCopy"><small>{r.total}</small><h3>{r.title}</h3><p>{r.subtitle}</p></div></button>)}</div>:
        <div className="archive">
          <div className="archiveTools">
            <div className="archiveFilters" aria-label="Filtrera alla recept">
              <label><span>NAMN</span><input value={archiveName} onChange={event=>setArchiveName(event.target.value)} placeholder="Sök på rättens namn"/></label>
              <label><span>PROTEIN</span><select value={archiveProtein} onChange={event=>setArchiveProtein(event.target.value)}>{proteins.map(value=><option key={value}>{value}</option>)}</select></label>
              <label><span>KOLHYDRAT</span><select value={archiveCarb} onChange={event=>setArchiveCarb(event.target.value)}>{carbs.map(value=><option key={value}>{value}</option>)}</select></label>
              {(archiveName||archiveProtein!=="Alla"||archiveCarb!=="Alla")&&<button className="clearFilters" onClick={()=>{setArchiveName("");setArchiveProtein("Alla");setArchiveCarb("Alla")}}>Rensa filter</button>}
            </div>
            <div className="archiveSort" aria-label="Sortera recept"><span>SORTERA EFTER</span>{([['name','Namn'],['protein','Protein'],['carb','Kolhydrat']] as const).map(([key,label])=><button className={sortBy===key?"active":""} onClick={()=>setSortBy(key)} key={key}>{label}</button>)}</div>
          </div>
          <div className="archiveLabels" aria-hidden="true"><span>Rätt</span><span>Viktigaste ingredienser</span><span>Total tid</span></div>
          <div className="archiveList">{archive.map((r,index)=><button key={r.id} className="archiveRow" onClick={()=>{setSelected(r);scrollTo(0,0)}}><span className="archiveNumber">{String(index+1).padStart(2,"0")}</span><span className="archiveName"><b>{r.swedishTitle}</b><small>{r.title}</small></span><span className="archiveIngredients">{importantIngredients(r)}</span><span className="archiveTime">◷ {r.total}</span><span className="archiveArrow" aria-hidden="true">↗</span></button>)}</div>
        </div>}
        {(showAll?archive.length:filtered.length)===0&&<div className="noResults"><b>Inga recept funna</b><span>Prova en annan kombination.</span></div>}
      </section>
    </>:<article className="recipePage">
      <section className="recipeHero"><div className="recipeTitle"><div className="ornament">— ♛ —</div><h1>{selected.title}</h1><h2>{selected.subtitle}</h2><p>{selected.description}</p></div><div className="heroDish">{selected.image?<img src={selected.image} alt={selected.swedishTitle}/>:<span>{selected.protein}</span>}</div></section>
      <section className="facts"><div><i className="factIcon" aria-hidden="true">◷</i><b>{selected.total}</b><span>Total tid</span></div><div><i className="factIcon" aria-hidden="true">♨</i><b>{selected.active} minuter</b><span>Aktiv tid</span></div><div><i className="factIcon" aria-hidden="true">◉</i><b>{selected.servings} portioner</b><span>Receptmängd</span></div><div><i className="factIcon" aria-hidden="true">▥</i><b>{selected.macros.kcal} kcal</b><span>Per portion</span></div><div><i className="factIcon" aria-hidden="true">⌂</i><b>{selected.occasion}</b><span>Passar som</span></div></section>
      <section className="recipeBody"><div className="paper ingredients"><h3>Ingredienser</h3>{selected.ingredients.map(g=><section key={g.heading}><h4>{g.heading}</h4><ul>{g.items.map(x=><li key={x}>{x}</li>)}</ul></section>)}</div><div className="paper method"><h3>Gör så här</h3>{selected.steps.map((s,i)=><section className="step" key={s.title}><i>{i+1}</i><div><h4>{s.title}</h4><ul>{s.items.map(x=><li key={x}>{x}</li>)}</ul></div></section>)}</div><aside><div className="paper"><h3>Serveringstips</h3><ul>{selected.tips.map(x=><li key={x}>{x}</li>)}</ul></div><div className="paper macros"><h3>Näringsvärde</h3><small>PER PORTION · BERÄKNAT</small>{Object.entries(selected.macros).map(([k,v])=><div key={k}><span>{{kcal:"Kalorier",protein:"Protein",carbs:"Kolhydrater",fat:"Fett",fiber:"Fiber"}[k]}</span><b>{v}{k==="kcal"?" kcal":" g"}</b></div>)}</div><div className="why"><h3>Varför det blir så gott</h3>{selected.why.map(x=><p key={x}>✓ {x}</p>)}</div></aside></section>
      <section className="community"><div><p className="kicker">MINA ANTECKNINGAR</p><h2>Smaka, minns, förbättra.</h2></div><div className="rating"><span>MITT BETYG</span><div>{[1,2,3,4,5].map(n=><button key={n} onClick={()=>rate(selected.id,n)} className={(ratings[selected.id]||0)>=n?"on":""} aria-label={`${n} stjärnor`}>★</button>)}</div></div><div className="actions"><button onClick={()=>setPanel("comment")}>Lägg till kommentar</button><button onClick={()=>setPanel("change")}>Föreslå ändring</button></div>{panel&&<form onSubmit={submitNote}><label>{panel==="comment"?"Kommentar":"Beskriv ändringen"}<textarea value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Skriv din anteckning här…"/></label><div><button type="button" onClick={()=>setPanel(null)}>Avbryt</button><button type="submit">Spara</button></div></form>}{(notes[selected.id]||[]).length>0&&<div className="notes">{notes[selected.id].map((n,i)=><p key={i}><span>{n.date}</span>{n.text}</p>)}</div>}</section>
      <button className="back" onClick={()=>{setSelected(null);scrollTo(0,0)}}>← Till receptarkivet</button>
    </article>}
    <footer><b>LE CARNET DU NORD</b><span>Lokalt i ditt hem · Aldrig publikt</span></footer>
  </main>
}
